## Database Properties
spring.datasource.url = jdbc:postgresql://ec2-54-235-92-43.compute-1.amazonaws.com:5432/d701bk4ead4vhp
spring.datasource.username = xgmjwmgyxxzeky
spring.datasource.password = ec463ab4b3aad12fa981fbc19cb889786999ce3e9c0aad31a757b755d0581bce

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

## Hibernate Logging
logging.level.org.hibernate.SQL= DEBUG

# Initialize the datasource with available DDL and DML scripts
spring.datasource.initialization-mode=always

## Jackson Properties
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS= false
spring.jackson.time-zone= UTC

## App Properties
app.jwtSecret= JWTSuperSecretKey
app.jwtExpirationInMs = 604800000

# Spring mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chikaproject2502@gmail.com
spring.mail.password=chika2502

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true
